---
AllCops:
  TargetRubyVersion: 2.4
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'

# Prefer &&/|| over and/or.
Style/AndOr:
  Enabled: true

# Do not use braces for hash literals when they are the last argument of a
# method call.
Style/BracesAroundHashParameters:
  Enabled: true
  EnforcedStyle: context_dependent
  Exclude:
    - 'lib/redis/distributed_store.rb'
    - 'test/redis/store/factory_test.rb'

# Align comments with method definitions.
Layout/CommentIndentation:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true
  Exclude:
    - 'redis-store.gemspec'

# In a regular class definition, no empty lines around the body.
Layout/EmptyLinesAroundClassBody:
  Enabled: true
  Exclude:
    - 'lib/redis/store/factory.rb'
    - 'test/redis/store/ttl_test.rb'

# In a regular method definition, no empty lines around the body.
Layout/EmptyLinesAroundMethodBody:
  Enabled: true

# In a regular module definition, no empty lines around the body.
Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/FirstParameterIndentation:
  Enabled: true

# Method definitions after `private` or `protected` isolated calls need one
# extra level of indentation.
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails

# Two spaces, no tabs (for indentation).
Layout/IndentationWidth:
  Enabled: true
  Exclude:
    - 'lib/redis/store/factory.rb'
    - 'lib/redis/store/namespace.rb'
    - 'test/redis/store/namespace_test.rb'

Layout/LeadingCommentSpace:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true
  Exclude:
    - 'test/redis/store/namespace_test.rb'

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true
  Exclude:
    - 'test/redis/store/redis_version_test.rb'

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

# Defining a method with parameters needs parentheses.
Style/MethodDefParentheses:
  Enabled: true

# Use `foo {}` not `foo{}`.
Layout/SpaceBeforeBlockBraces:
  Enabled: true
  Exclude:
    - 'lib/redis/store/namespace.rb'
    - 'redis-store.gemspec'
    - 'test/redis/store/namespace_test.rb'

# Use `foo { bar }` not `foo {bar}`.
Layout/SpaceInsideBlockBraces:
  Enabled: true
  Exclude:
    - 'lib/redis/distributed_store.rb'
    - 'lib/redis/store/factory.rb'
    - 'lib/redis/store/namespace.rb'
    - 'test/redis/store/factory_test.rb'
    - 'test/redis/store/namespace_test.rb'

# Use `{ a: 1 }` not `{a:1}`.
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  Exclude:
    - 'lib/redis/distributed_store.rb'
    - 'lib/redis/store.rb'
    - 'test/redis/distributed_store_test.rb'
    - 'test/redis/store/factory_test.rb'
    - 'test/redis/store/serialization_test.rb'
    - 'test/redis/store/ttl_test.rb'

Layout/SpaceInsideParens:
  Enabled: true

# Detect hard tabs, no hard tabs.
Layout/Tab:
  Enabled: true

# Blank lines should not have any spaces.
Layout/TrailingBlankLines:
  Enabled: true
  Exclude:
    - 'lib/redis/store.rb'
    - 'lib/redis/store/redis_version.rb'
    - 'test/redis/store/redis_version_test.rb'

# No trailing whitespace.
Layout/TrailingWhitespace:
  Enabled: true
  Exclude:
    - 'lib/redis/distributed_store.rb'
    - 'lib/redis/store/factory.rb'
    - 'test/redis/store/factory_test.rb'

# Use quotes for string literals when they are enough.
Style/UnneededPercentQ:
  Enabled: true

# Align `end` with the matching keyword or starting expression except for
# assignments, where it should be aligned with the LHS.
Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable
  AutoCorrect: true
  Exclude:
    - 'lib/redis/store/factory.rb'

# Use my_method(my_arg) not my_method( my_arg ) or my_method my_arg.
Lint/RequireParentheses:
  Enabled: true

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: true
  Exclude:
    - 'test/test_helper.rb'

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: true

# Prefer Foo.method over Foo::method
Style/ColonMethodCall:
  Enabled: true
  Exclude:
    - 'lib/redis/store/factory.rb'
